// BASE DE DONNÉES LOCALE DES ÉQUIPEMENTS DE THRONE AND LIBERTY (ÉPIQUE T2 & T3)
const TL_ITEMS_DB = [
    // ==========================================
    // --- ÉQUIPEMENTS ÉPIQUE T2 ---
    // ==========================================
    // --- ARMES T2 ---
    { name: "Lame du givre éternel de Deluzhnoa", rarity: "epic", tier: "T2", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/deluzhnoas_edge_of_eternal_frost" },
    { name: "Lame-tempête de Daigon", rarity: "epic", tier: "T2", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/daigons_stormblade" },
    { name: "Épée du chevalier inébranlable", rarity: "epic", tier: "T2", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/unshakeable_knights_sword" },
    { name: "Lame de la fortitude infernale", rarity: "epic", tier: "T2", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/blade_of_fiendish_fortitude" },
    { name: "Lame de ruine des Vermeil", rarity: "epic", tier: "T2", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crimson_doomblade" },
    { name: "Rempart de l'Enclume noire", rarity: "epic", tier: "T2", type: "weapon", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bulwark_of_the_black_anvil" },
    { name: "Rempart d'invulnérabilité", rarity: "epic", tier: "T2", type: "weapon", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bulwark_of_invulnerability" },
    { name: "Espadon de frénésie de Naru", rarity: "epic", tier: "T2", type: "weapon", icon: "sword2h", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/narus_frenzied_greatblade" },
    { name: "Lame martiale du cyclone céleste", rarity: "epic", tier: "T2", type: "weapon", icon: "sword2h", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/celestial_cyclone_warblade" },
    { name: "Lieuses du destin", rarity: "epic", tier: "T2", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/destiny_binders" },
    { name: "Arc de la clarté lunaire", rarity: "epic", tier: "T2", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/arc_of_lunar_radiance" },
    { name: "Arc à corde d'acier des Bercant", rarity: "epic", tier: "T2", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bercants_steelstring_bow" },
    { name: "Arc long de l'échine titanesque", rarity: "epic", tier: "T2", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/titanspine_longbow" },
    { name: "Persécutrices du clair de lune", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/moonlight_tormentors" },
    { name: "Arbalètes de la garde florépine des Bercant", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bercants_spineflower_crossbow" },
    { name: "Lance-piques cendreuses de la reine Bellandir", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/queen_bellandirs_toxic_spine_throwers" },
    { name: "Arbalètes de l'assaut implacable", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/unrelenting_annihilation_crossbows" },
    { name: "Arbalètes de saignée d'Akman", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/akman_s_bloodletter_crossbows" },
    { name: "Lance-épines de tempête de spores du Cordy", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/cordy_s_stormspore_spike_slingers" },
    { name: "Arbalètes de la nuit noire", rarity: "epic", tier: "T2", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/dark_night_crossbows" },
    { name: "Codex des profonds secrets", rarity: "epic", tier: "T2", type: "weapon", icon: "wand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/codex_of_the_deep_secrets" },
    { name: "Hymne du salut éternel", rarity: "epic", tier: "T2", type: "weapon", icon: "wand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/hymn_of_eternal_salvation" },
    { name: "Bâton spirituel d'ébène", rarity: "epic", tier: "T2", type: "weapon", icon: "staff", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ebony_spiritstaff" },
    { name: "Ranseur de joie meurtrière", rarity: "epic", tier: "T2", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/murderous_joy_ranseur" },
    { name: "Lance dentelée de Naru", rarity: "epic", tier: "T2", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/narus_serrated_spear" },
    { name: "Lance d'horreur insensée", rarity: "epic", tier: "T2", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/insane_horror_spear" },
    { name: "Pique infernale des Vermeil", rarity: "epic", tier: "T2", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crimson_s_infernal_spear" },
    { name: "Éclat cranté de Deluzhnoa", rarity: "epic", tier: "T2", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/deluzhnoa_s_notched_shard" },
    { name: "Orbe d'Eletrum", rarity: "epic", tier: "T2", type: "weapon", icon: "orb", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/electrum_orb" },
    { name: "Sphère d'ombres", rarity: "epic", tier: "T2", type: "weapon", icon: "orb", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/sphere_of_shadows" },
    { name: "Crocs incendiaires de Tevent", rarity: "epic", tier: "T2", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/dagger_aa_t2_polymorph_002" },

    // --- ARMURES T2 ---
    { name: "Barbute du courroux de l'oubli", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/barbute_of_wrath_of_oblivion" },
    { name: "Capuchon de la tempête transcendante", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/transcendental_storm_hood" },
    { name: "Couronne des liens de glace infinis", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crown_of_infinite_ice_bonds" },
    { name: "Couronne du héraut ardent", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crown_of_fiery_herald" },
    { name: "Heaume du légionnaire immortel", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/immortal_legionnaire_helmet" },
    { name: "Halo du point du jour", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/first_lights_halo" },
    { name: "Visage de l'annihilateur élu", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/visage_of_the_chosen_annihilator" },
    { name: "Visière du préteur royal", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/royal_praetors_visor" },
    { name: "Masque du lotus oublié", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/mask_of_the_forgotten_lotus" },
    { name: "Bicorne de l'amiral effroyable", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bicorne_of_the_dread_admiral" },
    { name: "Diadème du repos sacré", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/diadem_of_sacred_rest" },
    { name: "Masque de protection du seigneur de guerre éternel", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/protective_mask_of_the_eternal_warlord" },
    { name: "Masque de l'intendant spectral", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/mask_of_the_spectral_overseer" },
    { name: "Diadème du chercheur impérial", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/diadem_of_the_imperial_tracker" },
    { name: "Couronne du prophète sauvage", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crown_of_the_wild_prophet" },
    { name: "Visage du tyran infernal", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/face_of_the_infernal_tyrant" },
    { name: "Crâne couronné de la victoire", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/crowned_skull_of_victory" },
    { name: "Visière suprême de la Résistance", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/supreme_visor_of_the_resistance" },
    { name: "Capuche funèbre de la Résistance", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/funeral_hood_of_the_resistance" },
    { name: "Voile du seigneur de fer", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/iron_lord_s_veil" },
    { name: "Visière du héraut infernal", rarity: "epic", tier: "T2", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/infernal_herald_s_visor" },
    { name: "Mailles et plates du Fauche-roi", rarity: "epic", tier: "T2", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/king_reaper_s_mail_and_plates" },
    { name: "Plastron du courroux de l'oubli", rarity: "epic", tier: "T2", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/breastplate_of_wrath_of_oblivion" },
    { name: "Armure de plates du héraut infernal", rarity: "epic", tier: "T2", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/infernal_herald_s_plate_armor" },
    { name: "Cape du destin victorieux", rarity: "epic", tier: "T2", type: "armor", icon: "clover", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/cloak_of_victorious_destiny" },
    { name: "Aile dorée de l'empereur", rarity: "epic", tier: "T2", type: "armor", icon: "clover", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/golden_wing_of_the_emperor" },
    { name: "Caresse du traqueur du vide", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/caress_of_the_void_stalker" },
    { name: "Toucher de la tempête transcendante", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/touch_of_the_transcendental_storm" },
    { name: "Gants du héraut ardent", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_fiery_herald" },
    { name: "Gantelets du légionnaire immortel", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gauntlets_of_the_immortal_legionnaire" },
    { name: "Gants du point du jour", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_first_light" },
    { name: "Gants de l'annihilateur élu", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_chosen_annihilator" },
    { name: "Gantelets du préteur royal", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gauntlets_of_the_royal_praetor" },
    { name: "Gants du lotus oublié", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_forgotten_lotus" },
    { name: "Gants de l'amiral effroyable", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_dread_admiral" },
    { name: "Gants du repos sacré", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_sacred_rest" },
    { name: "Gantelets du seigneur de guerre éternel", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gauntlets_of_the_eternal_warlord" },
    { name: "Protège-mains de l'intendant spectral", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/hand_guards_of_the_spectral_overseer" },
    { name: "Gants du chercheur impérial", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_imperial_tracker" },
    { name: "Gants du prophète sauvage", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_the_wild_prophet" },
    { name: "Poigne du pacte démoniaque infernal", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/infernal_demonpact_grip" },
    { name: "Gants des profondeurs insondables", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gloves_of_unfathomable_depths" },
    { name: "Mitons des flammes infernales sournoises", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/mittens_of_sly_infernal_flames" },
    { name: "Gantelets suprêmes de la Résistance", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/supreme_gauntlets_of_the_resistance" },
    { name: "Gants funèbres de la Résistance", rarity: "epic", tier: "T2", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/funeral_gloves_of_the_resistance" },
    { name: "Pantalon du héraut ardent", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/pants_of_the_fiery_herald" },
    { name: "Pantalon du justicier divin", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/pants_of_the_divine_justiciar" },
    { name: "Solerets du préteur royal", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/sabatons_of_the_royal_praetor" },
    { name: "Bottes du lotus oublié", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/boots_of_the_forgotten_lotus" },
    { name: "Bottes de l'amiral effroyable", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/boots_of_the_dread_admiral" },
    { name: "Chaussures du repos sacré", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/shoes_of_the_sacred_rest" },
    { name: "Solerets du seigneur de guerre éternel", rarity: "epic", tier: "T2", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/sabatons_of_the_eternal_warlord" },

    // --- ACCESSOIRES T2 ---
    { name: "Sceau du soleil plongeant enchanté", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/enchanted_seal_of_the_plunging_sun" },
    { name: "Anneau d'instruction divine enchanté", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/enchanted_ring_of_divine_instruction" },
    { name: "Anneau de lumière céleste renforcé", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/reinforced_ring_of_celestial_light" },
    { name: "Solitaire de pureté", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/solitaire_of_purity" },
    { name: "Bague de chef de la Résistance renforcée", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/reinforced_ring_of_the_resistance_leader" },
    { name: "Anneau de châtiment lointain imprégné", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/imbued_ring_of_distant_retribution" },
    { name: "Symbole d'avancée de la nature imprégné", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/imbued_symbol_of_nature_s_advance" },
    { name: "Boucles d'oreilles de sang rubis imprégnées", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/imbued_ruby_blood_earrings" },
    { name: "Boucles d'oreilles royales étincelantes", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/sparkling_royal_earrings" },
    { name: "Larmes de granit doré renforcées", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/reinforced_tears_of_golden_granite" },
    { name: "Gorgerin draconique plongeant", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/draconic_plunging_gorget" },
    { name: "Gorgerin du glas inéluctable", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/gorget_of_the_inevitable_knell" },
    { name: "Collier de rituel ancestral", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ancestral_ritual_necklace" },
    { name: "Pendentif de rage barbare", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/pendentif_of_barbaric_rage" },
    { name: "Gorgerin draconique plongeant enchanté", rarity: "epic", tier: "T2", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/enchanted_draconic_plunging_gorget" },
    { name: "Manchettes dorées ancestrales", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ancestral_golden_cuffs" },
    { name: "Bracelet du contre-courant violent", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/bracelet_of_the_violent_counter_current" },
    { name: "Bracelet des mondes fracturés enchanté", rarity: "epic", tier: "T2", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/enchanted_bracelet_of_the_fractured_worlds" },
    { name: "Ceinture du maître chevalier", rarity: "epic", tier: "T2", type: "accessory", icon: "pocket", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/belt_of_the_master_knight" },
    { name: "Ceinture de l'apôtre royal enchantée", rarity: "epic", tier: "T2", type: "accessory", icon: "pocket", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/enchanted_belt_of_the_royal_apostle" },

    // ==========================================
    // --- ÉQUIPEMENTS ÉPIQUE T3 ---
    // ==========================================
    // --- ARMES T3 ---
    { name: "Lame suprême de la Résistance", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/supreme_blade_of_the_resistance" },
    { name: "Lame d'ivoire magnifique de Nerzatum", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/nerzatum_s_magnificent_ivory_blade" },
    { name: "Lame de cautérisation de Tchernobog", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/chernobog_s_cauterizing_blade" },
    { name: "Lame de la flamme dansante de Cornélius", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/cornelius_s_dancing_flame_blade" },
    { name: "Épée des cendres tombées de Nirma", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/nirma_s_fallen_ashes_sword" },
    { name: "Épée sans âme d'Ahzreil", rarity: "epic", tier: "T3", type: "weapon", icon: "sword", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ahzreil_s_soulless_sword" },
    { name: "Lame de boucher abyssale", rarity: "epic", tier: "T3", type: "weapon", icon: "sword2h", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/abyssal_butcher_blade" },
    { name: "Infâme espadon abyssal", rarity: "epic", tier: "T3", type: "weapon", icon: "sword2h", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/infamous_abyssal_greatsword" },
    { name: "Dagues suprêmes de la Résistance", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/supreme_daggers_of_the_resistance" },
    { name: "Crocs squelettiques de Nerzatum", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/nerzatum_s_skeletal_fangs" },
    { name: "Dagues d'écorchure de Minezerok", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/minezerok_s_flaying_daggers" },
    { name: "Dagues de la lune rouge de Kowazan", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/kowazan_s_red_moon_daggers" },
    { name: "Dagues perforantes du givre de Deluzhnoa", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/deluzhnoa_s_piercing_frost_daggers" },
    { name: "Dagues déviantes abyssales", rarity: "epic", tier: "T3", type: "weapon", icon: "dagger", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/abyssal_deviant_daggers" },
    { name: "Arc de l'obsession de Velentra", rarity: "epic", tier: "T3", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/velentra_s_arc_of_obsession" },
    { name: "Arc long du fléau du Grand Aélon", rarity: "epic", tier: "T3", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/grand_aelon_s_blight_longbow" },
    { name: "Arc du givre intense de Deluzhnoa", rarity: "epic", tier: "T3", type: "weapon", icon: "bow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/deluzhnoa_s_intense_frost_bow" },
    { name: "Persécutrices téméraires abyssales", rarity: "epic", tier: "T3", type: "weapon", icon: "crossbow", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/abyssal_reckless_tormentors" },
    { name: "Bâton incandescent de Talus", rarity: "epic", tier: "T3", type: "weapon", icon: "staff", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/talus_s_incandescent_staff" },
    { name: "Bâton de la lune carbonisée de Velentra", rarity: "epic", tier: "T3", type: "weapon", icon: "staff", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/velentra_s_charred_moon_staff" },
    { name: "Bâton de guerre immolé d'Aridus", rarity: "epic", tier: "T3", type: "weapon", icon: "staff", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/aridus_s_immolated_war_staff" },
    { name: "Ranseur super brûlant de Junobote", rarity: "epic", tier: "T3", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/junobote_s_super_hot_ranseur" },
    { name: "Lance glaciale du givre de Deluzhnoa", rarity: "epic", tier: "T3", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/deluzhnoa_s_glacial_frost_spear" },
    { name: "Arme d'hast punitive abyssale", rarity: "epic", tier: "T3", type: "weapon", icon: "spear", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/abyssal_punitive_polearm" },

    // --- ARMURES T3 ---
    { name: "Visière vertueuse de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/righteous_visor_of_the_resistance" },
    { name: "Armure de plates vertueuse de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/righteous_plate_armor_of_the_resistance" },
    { name: "Gantelets vertueux de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/righteous_gauntlets_of_the_resistance" },
    { name: "Grèves vertueuses de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/righteous_greaves_of_the_resistance" },
    { name: "Solerets vertueux de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/righteous_sabatons_of_the_resistance" },
    { name: "Capuche vaillante de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/valiant_hood_of_the_resistance" },
    { name: "Tunique vaillante de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/valiant_tunic_of_the_resistance" },
    { name: "Mitons vaillants de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/valiant_grips_of_the_resistance" },
    { name: "Chausses vaillantes de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/valiant_trousers_of_the_resistance" },
    { name: "Bottes vaillantes de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/valiant_boots_of_the_resistance" },
    { name: "Capuche noble de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/noble_hood_of_the_resistance" },
    { name: "Habit noble de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/noble_garment_of_the_resistance" },
    { name: "Gants nobles de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/noble_gloves_of_the_resistance" },
    { name: "Pantalon noble de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/noble_pants_of_the_resistance" },
    { name: "Chaussures nobles de la Résistance", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/noble_shoes_of_the_resistance" },
    { name: "Heaume du monstre d'acier", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/steel_juggernaut_great_helm" },
    { name: "Armure de plates du monstre d'acier", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/steel_juggernaut_platemail" },
    { name: "Gantelets du monstre d'acier", rarity: "epic", tier: "T3", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/steel_juggernaut_gauntlets" },
    { name: "Kilt du monstre d'acier", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/steel_juggernaut_kilt" },
    { name: "Bottes de plates du monstre d'acier", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/steel_juggernaut_plate_boots" },
    { name: "Casque de la dynastie déchue", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/fallen_dynasty_helmet" },
    { name: "Armure de plates de la dynastie déchue", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/fallen_dynasty_plate_armor" },
    { name: "Gantelets de la dynastie déchue", rarity: "epic", tier: "T3", type: "armor", icon: "hand", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/fallen_dynasty_gauntlets" },
    { name: "Jambières de plates de la dynastie déchue", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/fallen_dynasty_leg_plates" },
    { name: "Solerets de la dynastie déchue", rarity: "epic", tier: "T3", type: "armor", icon: "foot", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/fallen_dynasty_sabatons" },
    { name: "Masque du tueur de brutes", rarity: "epic", tier: "T3", type: "armor", icon: "shield", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/brute_slayer_mask" },
    { name: "Tunique du tueur de brutes", rarity: "epic", tier: "T3", type: "armor", icon: "shirt", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/brute_slayer_tunic" },

    // --- ACCESSOIRES T3 ---
    { name: "Anneau du messager d'argent", rarity: "epic", tier: "T3", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ring_of_the_silver_messenger" },
    { name: "Anneau des cauchemars infinis", rarity: "epic", tier: "T3", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ring_of_infinite_nightmares" },
    { name: "Anneau du crépuscule déclinant", rarity: "epic", tier: "T3", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ring_of_falling_dusk" },
    { name: "Anneau de la rétribution divine", rarity: "epic", tier: "T3", type: "accessory", icon: "ring", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/ring_of_divine_retribution" },
    { name: "Collier du monde souterrain", rarity: "epic", tier: "T3", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/underworld_necklace" },
    { name: "Collier de la sorcière maudite", rarity: "epic", tier: "T3", type: "accessory", icon: "gem", questlogUrl: "https://questlog.gg/throne-and-liberty/fr/db/item/cursed_witch_necklace" }
];
